forcemTLS: true
denyAuthorizationPolicy: true

extraIngresses: []
# - name: extraIngress
#   namespace: istio-system
#   annotations: 
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internal
#   rules:
#   - http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           service:
#             name: istio-ingressgateway
#             port:
#               number: 80

gateways: []
  # - name: ms-ingress
  #   namespace: istio-system
  #   annotations:
  #     foo: bar
  #   spec:
  #     selector: 
  #       istio: ingressgateway
  #     servers:
  #       - port:
  #           number: 80
  #           name: "http"
  #           protocol: "HTTP"
  #         hosts:
  #         - "*"

# to create a seperate ingress object change the istio-ingressgateway type to NodePort or ClusterIP
ingressForIngressGateway:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    # alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-3:***:certificate/fcaa9fd2-1b55-48d7-92f2-e829f7bafafd"
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  rules:
  - http:
      paths:
      # - path: /*
      #   backend:
      #     service:
      #       name: ssl-redirect
      #       port:
      #         number: use-annotation
      - pathType: Prefix
        path: /
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80

authorizationPolicy: []
# - name: auth-service-name
#   namespace: application-namespace 
#   action: ALLOW
#   rules:
#   - from:
#     - source:
#         principals: ["cluster.local/ns/default/sa/sleep"]
#     - source:
#         namespaces: ["test"]
#     to:
#     - operation:
#         methods: ["GET"]
#         paths: ["/info*"]
#     - operation:
#         methods: ["POST"]
#         paths: ["/data"]
#     when:
#     - key: request.auth.claims[iss]
#       values: ["https://accounts.google.com"]             
 