deployment:
  memoryMaxTrace: 50000
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
image:
  repository: docker.io/jaegertracing/all-in-one
  tag: 1.46.0
ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: internal-tools
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: jaeger-health-http
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0b0f62f5c9a6697d4,subnet-0afccdde86ef8e672,subnet-09a2db7fdac92e25c
    kubernetes.io/ingress.class: alb
  enabled: true
  rules:
  - http:
      paths:
      - backend:
          service:
            name: tracing
            port:
              number: 80
        path: /jaeger
        pathType: Prefix
namespace: istio-system
service:
  collector:
    type: ClusterIP
  tracing:
    type: NodePort
  zipkin:
    type: ClusterIP
volume:
  storage: 2Gi
  storageClassName: ""
