apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: "autoscaling"
        version: "v1"
        kind: "HorizontalPodAutoscaler"
      - group: "autoscaling"
        version: "v2"
        kind: "HorizontalPodAutoscaler"
      - group: "autoscaling"
        version: "v2beta2"
        kind: "HorizontalPodAutoscaler"
      - group: "policy"
        version: "v1"
        kind: "PodDisruptionBudget"
      - group: "keda.sh"
        version: "v1alpha1"
        kind: "ScaledObject"

