apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sallowedconfigmap
  annotations:
    description: Access allowed Configmap
    category: Security

spec:
  crd:
    spec:
      names:
        kind: K8sAllowedConfigmap
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedConfigmap:
              type: array
              items:
                type: string
            skipContainers:
              type: array
              items:
                type: string
            
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowedconfigmap
        import future.keywords.in

        # Check if containers are using allowed configmap
        violation[{"msg": msg}] {
          container := filtered_containers[_] 
          validate(container)
          msg := sprintf("Container %v in %v %v is not accessing the vaild configmap", [container.name, input.review.object.kind, input.review.object.metadata.name])
        }

        # Check if volume are using allowed configmap
        violation[{"msg": msg}] {
          volume := select_volume[_]
          validate_volume(volume)
          msg := sprintf("%v %v volume %v is not accessing the vaild configmap", [input.review.object.kind, input.review.object.metadata.name,volume.name])
        }

        validate(ctr){
          invaild := [good | config = ctr.env[_]; good = check_configmaps(config)]
          any(invaild)
        }

        validate(ctr){
          invaild := [good | config = ctr.envFrom[_]; good = check_configmaps(config)]
          any(invaild)
        }

        validate_volume(vlm){
          not input.parameters.allowedConfigmap[vlm.configMap.name]
        }

        check_configmaps(config){
          not input.parameters.allowedConfigmap[config.valueFrom.configMapKeyRef.name]
        }

        # filtered_containers returns containers and initContainers
        filtered_containers[c] {
          input.review.object.kind == "Pod"
          c := input.review.object.spec.containers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind == "Pod"
          c := input.review.object.spec.initContainers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind in ["Deployment", "StatefulSet", "Job"]
          c := input.review.object.spec.template.spec.containers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind in ["Deployment", "StatefulSet", "Job"]
          c := input.review.object.spec.template.spec.initContainers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind == "CronJob"
          c := input.review.object.spec.jobTemplate.spec.template.spec.containers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind == "CronJob"
          c := input.review.object.spec.jobTemplate.spec.template.spec.initContainers[_]
          check_for_allowedContainers(c) 
        }
       
        check_for_allowedContainers(ctr) = true {
          satisfied := [good | repo = input.parameters.skipContainers[_] ; good = ctr.name == repo]
          not any(satisfied)
        }

        select_volume[v]{
          input.review.object.kind == "Pod"
          v := input.review.object.spec.volumes[_]
        }

        select_volume[v]{
          input.review.object.kind in ["Deployment", "StatefulSet", "Job"]
          v := input.review.object.spec.template.spec.volumes[_]
        }

        select_volume[v]{
          input.review.object.kind == "CronJob"
          v := input.review.object.spec.jobTemplate.spec.template.spec.volumes[_]
        }

        