apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdisablehostnetworking
  annotations:
    description: Pods should not have host networking
    category: Security
spec:
  crd:
    spec:
      names:
        kind: K8sDisableHostNetworking
      validation:
        openAPIV3Schema:
          type: object
          properties:
            skipContainers:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdisablehostnetworking
        import future.keywords.in

        # Check for parent
        violation[{"msg": msg}] {
          validate(select_spec)
          msg = sprintf("%v %v should run on hostNetwork", [input.review.object.kind, input.review.object.metadata.name])
        }
        
        # Check if containers are overwriting parent
        violation[{"msg": msg}] {
          validate(filtered_containers[_])
          select_spec.securityContext.hostNetwork == false
          msg = sprintf("Container %v in your %v %v overwrites the parent and run on hostNetwork", [filtered_containers[i].name, input.review.object.kind, input.review.object.metadata.name])
        }

        # select_spec have all possible spec
        select_spec := ks {
          input.review.object.kind == "Pod"
          ks := input.review.object.spec
        }

        select_spec := ks {
          input.review.object.kind in ["Deployment", "StatefulSet", "Job"]
          ks := input.review.object.spec.template.spec
        }

        select_spec := ks {
          input.review.object.kind == "CronJob"
          ks := input.review.object.spec.jobTemplate.spec.template.spec
        }

        #validate check for hostNetwork
        validate(ctr) {
          ctr.securityContext.hostNetwork == true
        }

        # filtered_containers returns containers and initContainers
        filtered_containers[c]{
          c = select_spec.containers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c]{
          c = select_spec.initContainers[_]
          check_for_allowedContainers(c) 
        }

        check_for_allowedContainers(ctr) = true {
          satisfied := [good | repo = input.parameters.skipContainers[_] ; good = ctr.name == repo]
          not any(satisfied)
        }


