apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdisallowedhostipchostpid
  annotations:
    description: Container should not share Host IPC and process ID
    category: Security
spec:
  crd:
    spec:
      names:
        kind: K8sDisallowedHostIPCHostPID
      validation:
        openAPIV3Schema:
          type: object
          properties:
            skipContainers:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdisallowedhostipchostpid
        import future.keywords.in

        # Check HostIPC
        violation[{"msg": msg}] {
          container := filtered_containers[_]  
          container.securityContext.hostIPC == true
          msg = sprintf("Container %v in your %v %v should not share host IPC namespace", [container.name, input.review.object.kind, input.review.object.metadata.name])
        }

        # Check HostPID
        violation[{"msg": msg}] {
          container := filtered_containers[_]  
          container.securityContext.hostPID == true
          msg = sprintf("Container %v in your %v %v should not share host PID namespace", [container.name, input.review.object.kind, input.review.object.metadata.name])
        }

        # check for hostPID
        validate(ctr){
          ctr.securityContext.hostPID == true
        }
        
        filtered_containers[c] {
          input.review.object.kind == "Pod"
          c := input.review.object.spec.containers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind == "Pod"
          c := input.review.object.spec.initContainers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind in ["Deployment", "StatefulSet", "Job"]
          c := input.review.object.spec.template.spec.containers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind in ["Deployment", "StatefulSet", "Job"]
          c := input.review.object.spec.template.spec.initContainers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind == "CronJob"
          c := input.review.object.spec.jobTemplate.spec.template.spec.containers[_]
          check_for_allowedContainers(c) 
        }

        filtered_containers[c] {
          input.review.object.kind == "CronJob"
          c := input.review.object.spec.jobTemplate.spec.template.spec.initContainers[_]
          check_for_allowedContainers(c) 
        }
       
        check_for_allowedContainers(ctr) = true {
          satisfied := [good | repo = input.parameters.skipContainers[_] ; good = ctr.name == repo]
          not any(satisfied)
        }
