aws-load-balancer-controller:
  clusterName: eks-eks
  image:
    repository: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller
    tag: v2.4.6
  ingressClass: alb
  region: ap-south-1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  serviceAccount:
    annotations: {}
    create: true
    name: aws-load-balancer-controller
  vpcId: vpc-054d1a3db9b2d4c05
