{{ $v := .Values.extraIngresses }}
{{range $j, $ingress := $v }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{$ingress.name}}
  namespace: {{$ingress.namespace}}
  labels:
    app: {{$ingress.name}}
{{- if $ingress.annotations }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if $ingress.rules }}
  rules:
{{ toYaml $ingress.rules | indent 4 }}
{{- end }}
---
{{ end }}