apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-crd-delete
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kiali-crd-delete
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali-crd-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: kiali-crd-delete
    spec:
      serviceAccountName: kiali-crd-delete
      containers:
      - name: crd-delete
        image: {{ .Values.preDelete.images }}
        command: [sh, -c]
        args: ["kubectl delete kiali --all --all-namespaces && sleep {{.Values.preDelete.sleep}}"]
      restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali-crd-delete
rules:
- apiGroups:
  - "kiali.io"
  resources: ["*"]
  verbs:
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-crd-delete-binding
roleRef:
  kind: ClusterRole
  name: kiali-crd-delete 
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kiali-crd-delete
  namespace: {{ .Release.Namespace }}
