name: Helm-docs

on:
   pull_request:
    branches:
      - "main"
    types:
      - closed

env:
  HELM_DOCS_VERSION: "1.7.0"

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Pre-Commit Hooks
        run: |
          pip install pre-commit

      - name: Pre-Commit Hooks
        run: |
          pre-commit install
          pre-commit install-hooks

      - name: install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v${{env.HELM_DOCS_VERSION}}/helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          tar -xvf helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/sbin

      - name: run helm-docs
        run: |
          helm-docs -t README.md.gotmpl -o README.md
          git config --global user.email "github-service-ci@xebia.com"
          git config --global user.name "gitlab-service-ci"
          git add .
          git commit -m "README.md"
          git push -u origin main