name: Linting and Testing
on:
  pull_request:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v2.1

      - name: Helm Lint
        run: helm lint

