namespace: istio-system
image:
  repository: "docker.io/jaegertracing/all-in-one"
  tag: 1.44.0

service:
  tracing:
    type: ClusterIP
  zipkin:
    type: ClusterIP
  collector:
    type: ClusterIP

deployment:
  memoryMaxTrace: 50000
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

volume:
  storage: 2Gi
  storageClassName: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: jaeger
    #alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:account_id:certificate/certficate_arn
    #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-A,subnet-B
    alb.ingress.kubernetes.io/tags: Project Name=Xebia
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tracing
            port:
              number: 80