apiVersion: v2
name: helm-xebia-aws-ebs-csi-driver
description: A Helm chart to setup AWS EBS CSI driver
type: application
version: 0.2.0
appVersion: "1.16.0"
dependencies:
- name: aws-ebs-csi-driver
  version: "2.0.2"
  repository: "file://../charts/aws-ebs-csi-driver"

