authorizationPolicy: []
denyAuthorizationPolicy: false
extraIngresses: []
forcemTLS: true
gateways: []
ingressForIngressGateway:
  annotations:
    alb.ingress.kubernetes.io/group.name: istio-default
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
    alb.ingress.kubernetes.io/healthcheck-port: status-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0b0f62f5c9a6697d4,subnet-0afccdde86ef8e672,subnet-09a2db7fdac92e25c
    kubernetes.io/ingress.class: alb
  enabled: true
  rules:
  - http:
      paths:
      - backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80
        path: /
        pathType: Prefix
